<img src="logo.png">

# Gestión y análisis de datos.

In [2]:
import numpy as np

Debido a las características de los arreglos de *Numpy* para hacer "broadcasting", la biblioteca cuenta con una amplia gama de funciones se transmiten a los elementos seleccionados de un arreglo.

## Funciones trigonométricas.

### La función ```np.sin()```.

Regresa un arreglo en el que cada elemento es el seno de un ángulo expresado en radianes calculado a partir de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.sin.html

### La función ```np.cos()```.

Regresa un arreglo en el que cada elemento es el coseno de un ángulo expresado en radianes calculado a partir de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.cos.html

### La función ```np.tan()```.

Regresa un arreglo en el que cada elemento es la tangente de un ángulo expresado en radianes calculado a partir de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.tan.html

### La función ```np.sinh()```.

Regresa un arreglo en el que cada elemento es el seno hiperbólico de un ángulo expresado en radianes calculado a partir de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.sinh.html

### La función ```np.cosh()```.

Regresa un arreglo en el que cada elemento es el coseno hiperbólico de un ángulo expresado en radianes calculado a partir de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.cosh.html

### La función ```np.tanh()```.

Regresa un arreglo en el que cada elemento es la tangente hiperbólica de un ángulo expresado en radianes calculado a partir de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.tanh.html

### La función ```np.arcsin()```.

Regresa un arreglo en el que cada elemento corresponde ángulo expresado en radianes calculado a partir del inverso del seno de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.arcsin.html

### La función ```np.arccos()```.

Regresa un arreglo en el que cada elemento corresponde ángulo expresado en radianes calculado a partir del inverso del coseno de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.arccos.html

### La función ```np.arctan()```.

Regresa un arreglo en el que cada elemento corresponde ángulo expresado en radianes calculado a partir del inverso tangente de cada elemento del arreglo que se ingresa como argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.arctan.html

### La función ```np.arctan2()```.

Regresa un arreglo en el que cada elemento corresponde ángulo expresado en radianes calculado a partir del inverso la tangente formado por cada elemento del arreglo que se ingresa como primer argumento tomado como la longitud del lado opuesto y por cada elemento del arreglo que se ingresa como segundo argumento tomado como la longitud del lado adyacente.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.arctan.html

### La función ```np.arcsinh()```.

Regresa un arreglo en el que cada elemento corresponde ángulo expresado en radianes calculado a partir del inverso del seno hiperbólico formado por cada elemento del arreglo que se ingresa como primer argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.arcsinh.html

### La función ```np.arccosh()```.

Regresa un arreglo en el que cada elemento corresponde ángulo expresado en radianes calculado a partir del inverso del coseno hiperbólico formado por cada elemento del arreglo que se ingresa como primer argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.arccosh.html

### La función ```np.arctanh()```.

Regresa un arreglo en el que cada elemento corresponde ángulo expresado en radianes calculado a partir del inverso de la tangente hiperbólica formada por cada elemento del arreglo que se ingresa como primer argumento.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.arccosh.html

### La función ```np.arctan2h()```.

Regresa un arreglo en el que cada elemento corresponde ángulo expresado en radianes calculado a partir del inverso de la tangente hiperbólica calculada partir de dos arreglos que se ingresan como argumentos y que corresponden al lado opuesto y al adyacente.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.arctan2h.html

### La función  ```np.hypot()```.

Regresa un arreglo en el que cada elemento corresponde a la hipotenusa de un triángulo  rectángulo calculado a partir del inverso de la tangente hiperbólica calculada partir de dos arreglos que se ingresan como argumentos y que corresponden al lado opuesto y al adyacente.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.hypot.html

### Las funciones  ```np.deg2rad()``` y ```np.radians()```.

Estas funcones regresan un arreglo en el que cada elemento corresponde a un ángulo en radianes a partir de un arreglo que contiene ámgulos en grados.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.radians.html

### Las funciones  ```np.rad2deg()``` y ```np.degrees()```.

Estas funcones regresan un arreglo en el que cada elemento corresponde a un ángulo en grados a partir de un arreglo que contiene ángulos en radianes.

La documentación de dicha función se encuentra en:

https://numpy.org/doc/stable/reference/generated/numpy.degrees.html

**Ejemplos:**

In [7]:
opuesto = np.ones((4,4))

In [8]:
opuesto

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
adyacente = np.ones((4,4))

In [10]:
adyacente

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
angulo = np.arctan2(opuesto, adyacente)

In [12]:
angulo

array([[0.78539816, 0.78539816, 0.78539816, 0.78539816],
       [0.78539816, 0.78539816, 0.78539816, 0.78539816],
       [0.78539816, 0.78539816, 0.78539816, 0.78539816],
       [0.78539816, 0.78539816, 0.78539816, 0.78539816]])

In [13]:
np.degrees([0.78539816])

array([44.99999981])

In [14]:
np.degrees(angulo)

array([[45., 45., 45., 45.],
       [45., 45., 45., 45.],
       [45., 45., 45., 45.],
       [45., 45., 45., 45.]])

## Funciones da valor.

* ```np.abs()```
* ```np.around()```
* ```np.ceil()```
* ```np.exp()```
* ```np.exp2()```
* ```np.fabs()```
* ```np.fix()```
* ```np.floor()```
* ```np.log()```
* ```np.log10()```
* ```np.log1p()```
* ```np.log2()```
* ```np.logaddexp()```
* ```np.logaddexp2()```
* ```np.round()```

In [ ]:
numeros = np.array([[1.43, -1, 45.9999, -3.41],
                   [np.inf, -np.inf, np.inf, np.inf],
                   [np.nan, 13.45, 11, 21]])

In [ ]:
numeros

In [ ]:
np.abs(numeros)

In [ ]:
np.floor(numeros)

In [ ]:
np.ceil(numeros)

In [ ]:
np.round(numeros)

In [ ]:
np.log(numeros)

## Funciones de evaluación de arreglos.

* ```np.iscomplex()```
* ```np.isfinite()```
* ```np.isin()```
* ```np.isinf()```
* ```np.isnan()```
* ```np.isnat()```
* ```np.isneginf()```
* ```np.isposinf()```
* ```np.isreal()```
* ```np.isscalar()```

In [ ]:
numeros

In [ ]:
np.isfinite(numeros)

In [ ]:
np.isnan(numeros)

In [ ]:
np.isreal(numeros)

## Funciones lógicas.

* ```np.all()```
* ```np.any()```
* ```np.logical_and()```
* ```np.logical_not()```
* ```np.logical_or()```
* ```np.logical_xor()```

In [ ]:
booleana = np.array([[0, 1, 1],
                   [1, 0, 1],
                   [1, 1, 1,]], dtype=np.bool_)

In [ ]:
booleana

In [ ]:
np.any(booleana)

In [ ]:
np.all(booleana)

In [ ]:
np.all(booleana[2])

In [ ]:
np.logical_not(booleana)

In [ ]:
np.logical_or(booleana, True)

In [ ]:
otro_booleano = np.array([1, 0, 2], dtype=np.bool_)

In [ ]:
otro_booleano

In [ ]:
booleana

In [ ]:
np.logical_and(booleana, otro_booleano)

## Funciones polinomiales.

### La función  ```np.poly1d()```.

Esta función define un polinomio con coeficientes:

```
array[c1, c2, .... cn, c0]
```

$ c_1x^n + c_2x^{n-1} + ... + c_nx + c_o$

**Ejemplo:**

* La siguiente celda creará un arreglo que correponde al polinomio: 

$2x^4 + 4x^3 - 3x^2 + 0.5$

In [ ]:
ecuacion = np.poly1d([2, 4, -3, 0, 0.5])

In [ ]:
ecuacion

La siguiente celda calculará la derivada de ```ecuacion```, la cual da por resultado: 

$8x^3 + 12x^2 - 6x$

In [ ]:
np.polyder(ecuacion)

La siguiente celda calculará la integral indefinida de ```ecuacion```, la cual da por resultado: 

$0.4x^5 + x^4 -x^3 + 0.5x + c$

In [ ]:
np.polyint(ecuacion)

## Funciones estadísticas.

* ```np.amax()```
* ```np amin()```
* ```np.argmax()```
* ```np.argmin()```
* ```np.average()```
* ```np.correlate()```
* ```np.corrcoef()```
* ```np.count_nonzero()```
* ```np.cov()```
* ```np.cumprod()```
* ```np.cumsum()```
* ```np.histogram()```
* ```np.histogram2d()```
* ```np.histogram_bin_edges()```
* ```np.histogramdd()```
* ```np.max()```
* ```np.mean()```
* ```np.median()```
* ```np.min()```
* ```np.nanargmax()```
* ```np.nanargmin()```
* ```np.nancumprod()```
* ```np.nancumsum()```
* ```np.nanmax()```
* ```np.nanmean()```
* ```np.nanmedian()```
* ```np.nanmin()```
* ```np.nanpercentile()```
* ```np.nanquantile()```
* ```np.nanstd()```
* ```np.nansum()```
* ```np.nanvar()```
* ```np.percentile()```
* ```np.quantile()```
* ```np.std()```
* ```np.var()```

In [ ]:
numeros

In [ ]:
np.max(numeros)

In [ ]:
np.nanmax(numeros)

In [ ]:
np.nanmin(numeros)

In [ ]:
np.nanmean(numeros)

In [ ]:
np.nanmean(numeros[0])

In [ ]:
np.nanmean(numeros[2])

In [ ]:
np.nanmean(numeros[1])

In [3]:
aleatorios = np.random.randint(100,size=(20))

In [4]:
aleatorios

array([85, 13, 32,  6, 40, 89, 77, 45, 89, 70, 36, 28, 51,  1, 49, 20, 19,
       38, 39, 38])

In [5]:
np.histogram(aleatorios)

(array([2, 1, 2, 3, 4, 3, 0, 1, 1, 3], dtype=int64),
 array([ 1. ,  9.8, 18.6, 27.4, 36.2, 45. , 53.8, 62.6, 71.4, 80.2, 89. ]))